//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPPHelper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PCHData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PCHData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPPHelper.Resources.PCHData", typeof(PCHData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // stdafx.cpp : source file that includes just the standard includes
        ///// stdafx.obj will contain the pre-compiled type information
        ///
        ///#include &quot;stdafx.h&quot;
        ///
        ///// TODO: reference any additional headers you need in STDAFX.H
        ///// and not in this file.
        /// </summary>
        internal static string stdafx_cpp {
            get {
                return ResourceManager.GetString("stdafx_cpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // stdafx.h : include file for standard system include files,
        ///// or project specific include files that are used frequently, but
        ///// are changed infrequently
        /////
        ///#ifndef __$$ProjectName$$_STDAFX_H_INCLUDED__
        ///#define __$$ProjectName$$_STDAFX_H_INCLUDED__
        ///
        ///#define WIN32_LEAN_AND_MEAN		// Exclude rarely-used stuff from Windows headers
        ///// Common includes
        ///#include &quot;Common Files/ENGINE2 CLASS/defs.h&quot;
        ///
        ///// TODO: reference additional headers your program requires here
        ///
        ///#endif //__$$ProjectName$$_STDAFX_H_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stdafx_h {
            get {
                return ResourceManager.GetString("stdafx_h", resourceCulture);
            }
        }
    }
}
