//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSEOps.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>98.249.165.93:2479</string>\r\n  <string>98.129.220.124:3128</string>\r\n  <st" +
            "ring>96.4.198.192:80</string>\r\n  <string>95.142.161.84:80</string>\r\n  <string>94" +
            ".95.196.130:3128</string>\r\n  <string>94.236.54.7:80</string>\r\n  <string>94.236.5" +
            "4.5:80</string>\r\n  <string>94.198.47.6:3128</string>\r\n  <string>94.100.89.220:80" +
            "</string>\r\n  <string>93.187.120.18:3128</string>\r\n  <string>92.62.55.63:8080</st" +
            "ring>\r\n  <string>92.46.50.154:3128</string>\r\n  <string>89.189.85.43:80</string>\r" +
            "\n  <string>89.189.84.169:80</string>\r\n  <string>88.84.131.73:3128</string>\r\n  <s" +
            "tring>88.198.23.37:8080</string>\r\n  <string>86.122.120.6:80</string>\r\n  <string>" +
            "82.137.195.138:8080</string>\r\n  <string>80.193.72.145:80</string>\r\n  <string>77." +
            "21.21.112:80</string>\r\n  <string>75.151.116.33:8118</string>\r\n  <string>74.213.1" +
            "66.67:80</string>\r\n  <string>72.18.217.98:3128</string>\r\n  <string>72.167.181.9:" +
            "80</string>\r\n  <string>71.41.204.228:80</string>\r\n  <string>71.227.118.46:8080</" +
            "string>\r\n  <string>70.86.166.34:3128</string>\r\n  <string>70.124.10.219:8085</str" +
            "ing>\r\n  <string>69.59.90.86:2479</string>\r\n  <string>69.162.127.34:3128</string>" +
            "\r\n  <string>69.161.64.176:2479</string>\r\n  <string>69.141.58.197:8085</string>\r\n" +
            "  <string>69.136.230.175:8085</string>\r\n  <string>68.96.30.25:8080</string>\r\n  <" +
            "string>68.68.107.60:29505</string>\r\n  <string>68.39.206.217:8085</string>\r\n  <st" +
            "ring>68.233.8.69:80</string>\r\n  <string>68.168.96.173:80</string>\r\n  <string>67." +
            "192.61.164:808</string>\r\n  <string>67.11.20.236:8085</string>\r\n  <string>66.238." +
            "207.247:3128</string>\r\n  <string>64.74.246.35:80</string>\r\n  <string>64.71.141.1" +
            "48:3128</string>\r\n  <string>63.241.168.215:80</string>\r\n  <string>62.87.130.13:8" +
            "080</string>\r\n  <string>62.73.5.74:80</string>\r\n  <string>61.244.235.34:3128</st" +
            "ring>\r\n  <string>61.224.223.220:8088</string>\r\n  <string>61.180.78.254:8088</str" +
            "ing>\r\n  <string>60.190.223.54:808</string>\r\n  <string>60.10.164.83:808</string>\r" +
            "\n  <string>41.190.16.17:8080</string>\r\n  <string>41.134.13.66:8080</string>\r\n  <" +
            "string>24.49.156.155:8085</string>\r\n  <string>222.89.92.108:3128</string>\r\n  <st" +
            "ring>222.77.14.54:80</string>\r\n  <string>222.255.239.135:8080</string>\r\n  <strin" +
            "g>221.238.17.245:8080</string>\r\n  <string>221.214.27.253:808</string>\r\n  <string" +
            ">221.214.27.252:808</string>\r\n  <string>221.130.7.228:80</string>\r\n  <string>221" +
            ".130.7.226:80</string>\r\n  <string>221.130.162.244:80</string>\r\n  <string>221.130" +
            ".13.41:80</string>\r\n  <string>221.130.13.233:80</string>\r\n  <string>221.130.13.2" +
            "25:80</string>\r\n  <string>218.25.99.135:808</string>\r\n  <string>218.248.44.216:8" +
            "080</string>\r\n  <string>218.201.21.178:80</string>\r\n  <string>218.201.21.177:80<" +
            "/string>\r\n  <string>218.201.21.176:80</string>\r\n  <string>218.201.21.175:80</str" +
            "ing>\r\n  <string>218.201.21.158:80</string>\r\n  <string>217.111.163.142:80</string" +
            ">\r\n  <string>216.214.134.2:80</string>\r\n  <string>216.18.219.98:3128</string>\r\n " +
            " <string>213.42.178.199:80</string>\r\n  <string>213.41.80.9:80</string>\r\n  <strin" +
            "g>213.230.18.191:80</string>\r\n  <string>213.146.149.107:8080</string>\r\n  <string" +
            ">213.137.132.125:8080</string>\r\n  <string>213.131.1.102:3124</string>\r\n  <string" +
            ">212.73.111.163:8080</string>\r\n  <string>212.45.5.172:3128</string>\r\n  <string>2" +
            "12.244.60.45:8080</string>\r\n  <string>212.243.72.81:80</string>\r\n  <string>211.1" +
            "38.124.233:80</string>\r\n  <string>211.138.124.232:80</string>\r\n  <string>211.138" +
            ".124.211:80</string>\r\n  <string>211.138.124.210:80</string>\r\n  <string>211.138.1" +
            "24.200:80</string>\r\n  <string>211.138.124.199:80</string>\r\n  <string>211.138.124" +
            ".198:80</string>\r\n  <string>211.138.124.197:80</string>\r\n  <string>211.138.124.1" +
            "96:80</string>\r\n  <string>210.227.121.34:8888</string>\r\n  <string>210.125.84.17:" +
            "3124</string>\r\n  <string>208.96.213.149:80</string>\r\n  <string>208.77.151.84:80<" +
            "/string>\r\n  <string>208.77.151.82:80</string>\r\n  <string>207.249.174.3:80</strin" +
            "g>\r\n  <string>206.117.37.4:3127</string>\r\n  <string>204.236.224.235:80</string>\r" +
            "\n  <string>204.236.160.132:3128</string>\r\n  <string>202.189.126.85:3127</string>" +
            "\r\n  <string>202.171.42.7:3128</string>\r\n  <string>202.138.180.198:80</string>\r\n " +
            " <string>201.225.226.68:8080</string>\r\n  <string>201.134.185.163:3128</string>\r\n" +
            "  <string>200.96.53.7:8080</string>\r\n  <string>200.25.177.58:8080</string>\r\n  <s" +
            "tring>200.161.247.30:8080</string>\r\n  <string>200.119.31.2:8080</string>\r\n  <str" +
            "ing>199.26.254.69:3127</string>\r\n  <string>196.38.158.197:80</string>\r\n  <string" +
            ">196.38.158.196:80</string>\r\n  <string>196.12.187.29:8080</string>\r\n  <string>19" +
            "5.168.109.60:8080</string>\r\n  <string>195.14.0.99:3128</string>\r\n  <string>194.7" +
            "9.52.113:80</string>\r\n  <string>194.36.10.156:3128</string>\r\n  <string>193.191.1" +
            "48.227:3127</string>\r\n  <string>193.191.148.149:80</string>\r\n  <string>193.171.7" +
            "9.65:80</string>\r\n  <string>193.171.69.65:80</string>\r\n  <string>190.27.194.90:8" +
            "080</string>\r\n  <string>190.202.107.107:8080</string>\r\n  <string>189.21.214.194:" +
            "8080</string>\r\n  <string>187.5.20.236:6588</string>\r\n  <string>174.36.178.106:80" +
            "</string>\r\n  <string>174.143.150.83:80</string>\r\n  <string>174.142.24.206:3128</" +
            "string>\r\n  <string>174.142.24.203:3128</string>\r\n  <string>174.142.24.202:3128</" +
            "string>\r\n  <string>174.142.24.201:3128</string>\r\n  <string>174.142.104.57:3128</" +
            "string>\r\n  <string>164.78.252.25:80</string>\r\n  <string>164.78.252.110:80</strin" +
            "g>\r\n  <string>147.83.30.164:3128</string>\r\n  <string>146.57.249.99:3128</string>" +
            "\r\n  <string>146.57.249.98:3127</string>\r\n  <string>140.114.79.233:3128</string>\r" +
            "\n  <string>138.251.214.78:3128</string>\r\n  <string>137.165.1.111:3128</string>\r\n" +
            "  <string>131.247.2.242:3124</string>\r\n  <string>131.179.50.70:3127</string>\r\n  " +
            "<string>129.186.205.76:3128</string>\r\n  <string>129.105.15.37:3127</string>\r\n  <" +
            "string>128.42.142.42:3124</string>\r\n  <string>128.42.142.41:3124</string>\r\n  <st" +
            "ring>128.112.139.108:3127</string>\r\n  <string>125.234.47.218:80</string>\r\n  <str" +
            "ing>123.202.26.71:9415</string>\r\n  <string>122.154.17.148:3128</string>\r\n  <stri" +
            "ng>121.10.120.214:80</string>\r\n  <string>118.97.72.37:80</string>\r\n  <string>118" +
            ".70.127.55:8080</string>\r\n  <string>118.232.153.177:9415</string>\r\n  <string>112" +
            ".78.196.95:3128</string>\r\n  <string>112.4.106.88:808</string>\r\n  <string>109.123" +
            ".84.217:80</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Proxies {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Proxies"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kreuzerkrieg.dyndns.info/Kreuzerkrieg1.htm")]
        public string sPage4BingSEO {
            get {
                return ((string)(this["sPage4BingSEO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int jCount4BingSEO {
            get {
                return ((int)(this["jCount4BingSEO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iCount4BingSEO {
            get {
                return ((int)(this["iCount4BingSEO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kreuzerkrieg.dyndns.info/Kreuzerkrieg1.htm")]
        public string sPage4YahooSEO {
            get {
                return ((string)(this["sPage4YahooSEO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int jCount4YahooSEO {
            get {
                return ((int)(this["jCount4YahooSEO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iCount4YahooSEO {
            get {
                return ((int)(this["iCount4YahooSEO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kreuzerkrieg.dyndns.info/Kreuzerkrieg1.htm")]
        public string sPage4GoogleSEO {
            get {
                return ((string)(this["sPage4GoogleSEO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int jCount4GoogleSEO {
            get {
                return ((int)(this["jCount4GoogleSEO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iCount4GoogleSEO {
            get {
                return ((int)(this["iCount4GoogleSEO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stock photos kreuzerkrieg")]
        public string BuzzWords {
            get {
                return ((string)(this["BuzzWords"]));
            }
        }
    }
}
